site_name: thehive4py
repo_name: TheHive-Project/TheHive4py
repo_url: https://github.com/TheHive-Project/TheHive4py
nav:
  - TheHive4py: index.md
  - Examples: 
    - Client: examples/client.md
    - Alert: examples/alert.md
    - Case: examples/case.md
  - Reference: 
    - Client: reference/client.md
    - Endpoints: reference/endpoints.md
    - Errors: reference/errors.md
    - Query: reference/query.md
    - Session: reference/session.md
    - Types: reference/types.md
    - Helpers: reference/helpers.md

  - Release Notes: release-notes.md
theme:
  name: material
  favicon: img/strangebee.png
  logo: img/strangebee.png
  features:
    - content.code.copy
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: custom
      accent: custom
      toggle: 
        icon: material/lightbulb-outline
        name: Switch to system preference
extra_css: 
  - styles/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  social:
    - icon: simple/discord
      link: https://discord.com/invite/XhxG3vzM44
      name: Discord
    - icon: simple/github
      link: https://github.com/TheHive-Project/TheHive4py
      name: GitHub
    - icon: simple/python
      link: https://pypi.org/project/thehive4py/
      name: PyPI
  version:
    provider: mike
plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://requests.readthedocs.io/en/stable/objects.inv
          options:
            show_root_heading: true
            show_root_full_path: true
            merge_init_into_class: true
            show_source: true
            show_if_no_docstring: true
            members_order: source
            docstring_section_style: table
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
watch: 
  - examples 
  - thehive4py