name: check-release-notes
on: 
  workflow_call:
jobs:
  build:
    name: Check release notes 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.13
      - name: Install dependencies
        run: pip install --no-cache-dir -U pip .['dev']
      - name: Check release notes
        run: nox --session=check-release-notes
