name: deploy-docs
on: 
  workflow_call:
jobs:
  upload:
    name: Deploy docs to github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.13
      - name: Install dependencies
        run: pip install --no-cache-dir -U pip .['dev']
      - name: Configure git
        run: |
          git fetch origin gh-pages --depth=1
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Deploy to github pages
        run: nox --session=deploy-docs
